version: 2

models:
  - name: dim_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: dim_stores
    columns:
      - name: store_id
        tests: [not_null, unique]
