CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
  TRANSACTION_ID VARCHAR,
  USER_ID VARCHAR,
  PRODUCT_ID VARCHAR,
  STORE_ID VARCHAR,
  PAYMENT_METHOD VARCHAR,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER,
  DISCOUNT NUMBER,
  AMOUNT NUMBER,
  TRANSACTION_DATE TIMESTAMP
);